language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
script:
  - "python -m unittest discover tests"
  - "coverage run -m unittest discover -s tests"
after_success: coveralls
cache: pip
